// login
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

// Pastes
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CLEAR = "CART_CLEAR"
export const CARD_ADD_SINGLE_ITEM = "CARD_ADD_SINGLE_ITEM";
export const CART_INCREMENT_ITEM = "CART_INCREMENT_ITEM";
export const CART_DECREMENT_ITEM = "CART_DECREMENT_ITEM";
export const RECENT_ORDER = "RECENT_ORDER";
export const PUSH_RECENT_ORDER = "PUSH_RECENT_ORDER";


export const RECENT_UPDATED_TIMESTAMP = "RECENT_UPDATED_TIMESTAMP";
